### PR TITLE
Enable access control via the OpenID Connect provider

### LINKED ISSUE #1: Feature Request: Set user properties via Identity Provider
I was thinking about a feature, where it would be possible to set user properties like is_admin, canCreate and readOnly in the IdP instead of/additional to the settings.json.

### PR DESCRIPTION
**Pull request by rhansen**
@B00tLoad Would you test this to see if it meets your needs? You can install it by running the following in your Etherpad root directory:
```
npm i --no-save --legacy-peer-deps ether/ep_openid_connect#rhansen-userprops
```

Fixes #1

### CODE REVIEW

**Comment by B00tLoad** [comment]
I tried to install it and got the following error message.

> Console error
> ```
> npm ERR! code 1
> npm ERR! Command failed: git checkout userprops
> npm ERR! error: pathspec 'userprops' did not match any file(s) known to git
> npm ERR!
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-03-15T15_10_57_091Z-debug.log
> ```

> debug.log
> ```
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node',
> 1 verbose cli   '/usr/bin/npm',
> 1 verbose cli   'i',
> 1 verbose cli   'ether/ep_openid_connect#userprops' ]
> 2 info using npm@6.14.4
> 3 info using node@v10.19.0
> 4 verbose npm-session a99b9d2400c33806
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData error for github:ether/ep_openid_connect#userprops Command failed: git>
> 7 silly fetchPackageMetaData error: pathspec 'userprops' did not match any file(s) known to git
> 8 timing stage:rollbackFailedOptional Completed in 1ms
> 9 timing stage:runTopLevelLifecycles Completed in 4467ms
> 10 verbose stack Error: Command failed: git checkout userprops
> 10 verbose stack error: pathspec 'userprops' did not match any file(s) known to git
> 10 verbose stack
> 10 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
> 10 verbose stack     at ChildProcess.emit (events.js:198:13)
> 10 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 11 verbose cwd /opt/etherpad
> 12 verbose Linux 5.4.0-64-generic
> 13 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "ether/ep_openid_connect#userprops"
> 14 verbose node v10.19.0
> 15 verbose npm  v6.14.4
> 16 error code 1
> 17 error Command failed: git checkout userprops
> 17 error error: pathspec 'userprops' did not match any file(s) known to git
> 18 verbose exit [ 1, true ]
> ```

**Comment by rhansen** [comment]
Whoops, I gave you the wrong branch name. Try this @B00tLoad:

```shell
npm i --no-save --legacy-peer-deps ether/ep_openid_connect#rhansen-userprops
```

**Comment by B00tLoad** [comment]
@rhansen since installing, I only get 502 or 504 status codes (using nginx as reverse proxy), service status is "running", when trying to wget the index page localhost I get no response

**Comment by rhansen** [comment]
I am unable to reproduce. Questions:
* Any error messages in the server's logs?
* Do the logs show "ep_openid_connect - Client discovery complete. Configured."?
* Do the logs show "server - Etherpad is running"?
* If you visit Etherpad directly (not via the reverse proxy) do you get anything?
* Did you make any changes to your settings.json? If so, undo those and it should work like it used to.

**Comment by rasos** [comment]
I would like to test the use case that anybody can edit, but only authenticated users are allowed to create a pad. So I guess I would need to set: 

```
  "ep_openid_connect": {
    "scope": ["openid", "etherpad"],
    "user_properties": {
      "is_admin": {"claim": "etherpad_is_admin"},
      "canCreate": {"claim": "etherpad_canCreate"}
    }
  },
```
Am I correct that editing remains as a default permission? I can't find an explicit `canEdit` permission in etherpad code.

**Comment by rhansen** [comment]
> I would like to test the use case that anybody can edit, but only authenticated users are allowed to create a pad.

With core Etherpad, authentication is either required or it isn't used at all; there is no concept of optional authentication. To get the behavior you want you would need to install a plugin that "authenticates" guests in a manner similar to the [ep_readonly_guest](https://www.npmjs.com/package/ep_readonly_guest) plugin. (That plugin only supports read-only guests; it would need to be tweaked to support guest users that are able to edit existing pads but not create new pads. Feel free to open a feature request.)

Once you have such a plugin, you would then configure ep_openid_connect like this:

```json
  "ep_openid_connect": {
    "scope": ["openid", "etherpad"],
    "user_properties": {
      "is_admin": {"claim": "etherpad_is_admin"},
      "canCreate": {"default": true}
    }
  },
```

Or, if you don't care about granting admin access, you can simplify the config:

```json
  "ep_openid_connect": {
    "user_properties": {
      "canCreate": {"default": true}
    }
  },
```

> Am I correct that editing remains as a default permission?

Anyone can edit by default.

> I can't find an explicit `canEdit` permission in etherpad code.

It's called [`readOnly`](https://github.com/ether/etherpad-lite/blob/e31da37d0003accd303ef9eb557b5bd92f62db14/settings.json.template#L419-L420).

**Comment by rhansen** [comment]
@B00tLoad Were you able to get this working?

**Comment by rhansen** [comment]
Friendly ping @B00tLoad

**Comment by B00tLoad** [comment]
My stupid ass hyperfixated on completely different things after I was stuck trying to get the server to work properly after updating. I now finally ended up spending the last day to reinstall it on a new clean server.
I installed the plugin and now wehenever I try to open a pad, it seems to get stuck while compressing "etherpad-lite/node_modules/ep_openid_connect/static/js/client.js".

I'd love to provide a logfile, but I somehow am unable to find them. I promise I won't need 3 months again for answering... So sorry for that.

**Comment by rhansen** [comment]
> it seems to get stuck while compressing "etherpad-lite/node_modules/ep_openid_connect/static/js/client.js"

What do you mean? How do you know that it's getting stuck while compressing that file?

> I'd love to provide a logfile, but I somehow am unable to find them.

The log is written to standard out. How are you starting Etherpad?

**Comment by B00tLoad** [comment]
For purposes of testing I start it via the fastRun.sh file. (from the etherpad-dir: "./bin/fastRun.sh --settings settings-bm.json")
I thought that it got stuck with the client.js because that's where everything stoped last time.
`[2021-07-12 19:56:01.090] [INFO] Minify - Compress JS file /opt/etherpad/etherpad-lite/node_modules/ep_openid_connect/static/js/client.js.` 
However when retrying today it stopped with repeatedly showing "Failed authentication from IP 127.0.0.1" every ~90 seconds which it didn't do last time.

**Comment by rhansen** [comment]
Would you [enable `DEBUG` logging](https://github.com/ether/etherpad-lite/blob/336d48add73a7d22191d810cc68855ecd72c11a5/settings.json.template#L586-L591) and paste the full output?

**Comment by B00tLoad** [comment]
Couldn't even load the front page today, log here: [https://gist.github.com/B00tLoad/a220fbd0ba9c1b7d4b450b16561b75c7](https://gist.github.com/B00tLoad/a220fbd0ba9c1b7d4b450b16561b75c7)

Running the `node --trace-deprecation ...` output the following:
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/opt/etherpad/etherpad-lite/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by rhansen** [comment]
Your issues do not seem related to ep_openid_connect. In particular, npm is at the wrong version (v7.18.1 when it should be v6.14.13). I recommend running `./bin/installDeps.sh`. If that doesn't work, try reinstalling from scratch.

**Comment by B00tLoad** [comment]
TBH i feel kinda incompetent...
I did a clean reinstall with only hash_auth and openid_connect (with the branch you gave me in this comment: https://github.com/ether/ep_openid_connect/pull/3#issuecomment-800660376) installed and the previous settings imported. Now I get a error with npm and the lockfileversion being incompatible and then the server stopped.
Log: https://gist.github.com/B00tLoad/1e22a426c76184d26ce7f9beda833610

**Comment by rhansen** [comment]
Delete `/opt/etherpad/etherpad-lite/package*.json` and try running it again. (There are some frustrating incompatibilities between npm v6 and v7. If the plugins were installed using npm v7 without the right command-line flags then these incompatibilities will cause problems during Etherpad startup.)

Also, why are you installing ep_hash_auth? I don't think it's incompatible with ep_openid_connect, but I find it odd you're installing two unrelated authentication plugins.

**Comment by B00tLoad** [comment]
Alright thanks. It works now (as far as "it starts" at least, gotta test the rest tomorrow or the day thereafter). 

I'm using the ep_hash_auth right now because I also have a local admin account in the config currently. I haven't fount any incompatebilities yet, but that's also more of a temporary thing.

**Pull request merged**
